import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { Inter } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export default async function RootLayout({ children }: LayoutProps<"/">) {

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.className)}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-right" richColors />
        {/* <Navbar /> */}

        {children}
        {/* Footer */}
      </body>
    </html>
  );
}
